# Datasets from the first hospital of Zhejiang University

We used four OSCC cohorts in this study. For the CODEX, Polaris, and Xenium cohorts, formalin-fixed, paraffin-embedded (FFPE) blocks were collected from patients diagnosed with oral squamous cell carcinoma (OSCC) who underwent curative surgery at the First Affiliated Hospital of Zhejiang University between October 2017 and March 2025. Clinical and pathological records, along with follow-up data, were retrospectively reviewed. The primary endpoints were recurrence and/or metastasis. This study was approved by the Ethics Committee of the First Affiliated Hospital of Zhejiang University and was conducted in accordance with Institutional Review Board (IRB) protocols.

**Cohort 1.** The CODEX cohort comprised 63 samples from 60 treatment-naïve patients, including 56 primary tumor samples and 7 adjacent normal tissue samples. One tumor sample was excluded because of staining failure. Information on this cohort is shown in Supplementary Table 1.

**Cohort 2.** The Polaris cohort, analyzed by multiplex immunofluorescence (mIHC), comprised 115 samples from 101 patients. These included primary tumor samples from 96 patients and matched recurrent tumor samples from 11 of these individuals. Most patients (n = 96) were treatment-naïve prior to surgery. The remaining five patients received neoadjuvant induction chemotherapy; postoperative specimens were obtained, and pretreatment biopsy samples were also available for three patients. One sample was excluded from the cohort because of imaging failure. Seven samples were excluded from subsequent analysis because of a lack of CD44 expression. Information on this cohort is shown in Supplementary Table 2.

**Cohort 3.** This cohort was obtained from published single-cell RNA sequencing (scRNA-seq) datasets. Information on this cohort is shown in Supplementary Table 3.

**Cohort 4.** The Xenium cohort comprised 40 primary OSCC samples from 40 treatment-naïve patients (24 samples overlap with those in cohort 2). Information on this cohort is shown in Supplementary Table 4.
